version: '{build}'

branches:
  only:
  - master

nuget:
  disable_publish_on_pr: true

skip_commits:
  message: /docs(.*):/

build_script:
- ps: sln\Build-Package.ps1

test: off

artifacts:
- path: sln\src\NSpec\publish\*.nupkg
  name: NSpec
- path: sln\src\DotNetTestNSpec\publish\*.nupkg
  name: DotNetTestNSpec

deploy:
- provider: NuGet
  name: Development
  server: https://www.myget.org/F/nspec/api/v2/package
  api_key:
    secure: fLdJBSqSl6dP8rxk7vNJMYQxGchdEfMpOSF0DxKJJMmyfMaW+0Gx139YA3QxwXWm
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: Production
  api_key:
    secure: yC++3vJi0VQue3koutRC6PWdbN1uuXqXYvaAZTA3SZq6UKuJP5hKx6JhgkdOI8/M
  on:
    branch: master
    appveyor_repo_tag: true